# Generated by Django 5.2.9 on 2025-12-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetModule',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('module_type', models.CharField(choices=[('CUADRUPLA', 'Cuádrupla'), ('TRIPLA', 'Tripla')], max_length=10)),
                ('in_service_date', models.DateField()),
                ('total_accumulated_km', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(choices=[('IQ', 'Inspección Quincenal'), ('B', 'Inspección Bimestral'), ('A', 'Revisión Anual'), ('BI', 'Revisión Bianual'), ('P', 'Reparación Pentanual'), ('DE', 'Reparación Decanual')], help_text='Abreviatura normativa del ciclo (p. ej., IQ, B, A, BI, P, DE)', max_length=4, unique=True)),
                ('maintenance_type', models.CharField(choices=[('LIVIANO', 'Liviano'), ('PESADO', 'Pesado')], default='LIVIANO', max_length=10)),
                ('km_interval', models.PositiveIntegerField(blank=True, help_text='Kilometraje máximo permitido antes de la próxima intervención.', null=True)),
                ('time_interval_days', models.PositiveIntegerField(blank=True, help_text='Cantidad de días máximos antes de la próxima intervención.', null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['maintenance_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(help_text='Lectura de odómetro al momento del mantenimiento.')),
                ('notes', models.TextField(blank=True)),
                ('fleet_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='maintenance.fleetmodule')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.maintenanceprofile')),
            ],
            options={
                'ordering': ['-event_date', 'fleet_module'],
                'unique_together': {('fleet_module', 'profile', 'event_date')},
            },
        ),
        migrations.CreateModel(
            name='OdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('odometer_reading', models.PositiveIntegerField(help_text='Lectura acumulada de odómetro del módulo en la fecha indicada.')),
                ('daily_delta_km', models.IntegerField(blank=True, help_text='Diferencia de kilómetros recorridos desde la última lectura registrada.', null=True)),
                ('fleet_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='maintenance.fleetmodule')),
            ],
            options={
                'ordering': ['fleet_module', 'reading_date', 'id'],
                'unique_together': {('fleet_module', 'reading_date')},
            },
        ),
    ]
